### ISSUE TITLE
Correct location for installation of create_ap.resume (systemd file)

### ISSUE THREAD

**Issue by exuvo** [dlenski/create_ap#1]
Your new lines for 
`$(DESTDIR)/lib/systemd/system-sleep/create_ap.resume`
 should be 
`$(DESTDIR)$(PREFIX)/lib/systemd/system-sleep/create_ap.resume`

**Comment by exuvo** [comment]
Fixed with https://github.com/exuvo/create_ap/commit/3315614b6eb261639611f7c5c9e9f3b4e0d13f0d

**Comment by dlenski** [comment]
Sorry for the horribly delayed reply :sob: . As I wrote in the commit message of https://github.com/dlenski/create_ap/commit/380e4f4d857d22b958fe6612a08462ac58ca51b0,

> For unclear reasons, this only works in /lib/systemd/system-sleep, not in /usr/lib/systemd/system-sleep.

Does it work for _you_ in `/usr/lib`? What OS are you using?

**Comment by exuvo** [comment]
I think it worked, i dont sleep my computer much anymore due to a bugged peripheral. Archlinux.
