### ISSUE TITLE
Mismatch of setting name DTIM_INTERVAL and DTIM_PERIOD in example config.

### ISSUE THREAD

**Issue by exuvo** [dlenski/create_ap#2]
The config example has a DTIM_INTERVAL but the script is looking for DTIM_PERIOD. period seems correct as that is what hostapd uses.

**Comment by exuvo** [comment]
Fixed with https://github.com/exuvo/create_ap/commit/5f9978777f8eb87f3c6c3ff87b8ccaa8a4300241

**Comment by dlenski** [comment]
Thank you, cherry-picked!
